name: Vercel Production Deployment
env:
  VERCEL_PROJECT_ID: prj_WgAwiEn8npZcGBD9wPc76jKA3XxB
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=2JQfttEdd5ElYkSXV4SwgV8n
      - name: Build Project Artifacts
        run: vercel build --prod --token=2JQfttEdd5ElYkSXV4SwgV8n
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=2JQfttEdd5ElYkSXV4SwgV8n
